# sudo docker-compose build
# sudo docker-compose up

# Subir em background
# sudo docker-compose -f ubuntu_apache_php70_pdo_db.yml up -d

# How use iterative mode container
# sudo docker-compose exec ubuntu_apache_php bash

#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: "2"
services:
  apache_php:
    build:
      dockerfile: Dockerfile
      context: .
    image: ubuntu18_apache_php72:18.04
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    links: 
      - db
      - db-academico
    networks: 
      - default
  db:
    image: mysql:5.7.10
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: myDb
    volumes: 
      - mysql-data:/var/lib/mysql
    networks: 
      - default

  db-academico:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "AnotherPassw0rd"
      MSSQL_PDI: Developer
    ports:
      - "1433:1433"
    volumes:
      - academico-data:/var/opt/mssql



# networks:
#   formdin-network:
#     driver: bridge
volumes: 
    mysql-data:
    academico-data:
        