-- Exportação Alunos
SELECT A.* FROM ALUNOS A
INNER JOIN MATRICULAS M ON A.COD_ALUNO = M.COD_ALUNO
WHERE M.COD_INSTITUICAO = 3 AND
      (M.COD_CURSO = 80 OR M.COD_CURSO = 851 OR M.COD_CURSO = 862);

--  Exportação Cursos
SELECT * FROM CURSOS WHERE (COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862);

SELECT * FROM MATRICULAS WHERE COD;

-- Exportação Disciplinas
SELECT DISCIPLINAS.* FROM DISCIPLINAS
INNER JOIN DISCIPLINAS_MATRIZES_CURRICULARES ON DISCIPLINAS.COD_DISCIPLINA = DISCIPLINAS_MATRIZES_CURRICULARES.COD_DISCIPLINA
INNER JOIN MATRIZES_CURRICULARES ON DISCIPLINAS_MATRIZES_CURRICULARES.COD_MATRIZ_CURRICULAR = MATRIZES_CURRICULARES.COD_MATRIZ_CURRICULAR
WHERE COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862 ;

-- Exportação Disciplinas Matrizes Curriculares
SELECT DISCIPLINAS_MATRIZES_CURRICULARES.* FROM DISCIPLINAS_MATRIZES_CURRICULARES
INNER JOIN MATRIZES_CURRICULARES ON DISCIPLINAS_MATRIZES_CURRICULARES.COD_MATRIZ_CURRICULAR = MATRIZES_CURRICULARES.COD_MATRIZ_CURRICULAR
WHERE COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862;

-- Exportação Instituições
SELECT * FROM INSTITUICOES WHERE COD_INSTITUICAO = 3;

-- Exportação Matrículas
SELECT * FROM MATRICULAS WHERE (COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862);

SELECT * FROM CURSOS WHERE COD_CURSO = 80;
-- Exportação Matrículas Pautas
SELECT MATRICULAS_PAUTAS.* FROM MATRICULAS_PAUTAS
INNER JOIN MATRICULAS M on MATRICULAS_PAUTAS.COD_MATRICULA = M.COD_MATRICULA
WHERE COD_TIPO_CURSO = 265 AND (COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862);

-- Exportação Matrizes Curriculares
SELECT * FROM MATRIZES_CURRICULARES WHERE (COD_CURSO = 80 OR COD_CURSO = 851 OR COD_CURSO = 862);

-- Exportação Pautas
SELECT * FROM PAUTAS
INNER JOIN MATRICULAS_PAUTAS MP on PAUTAS.COD_PAUTA = MP.COD_PAUTA
INNER JOIN MATRICULAS M on MP.COD_MATRICULA = M.COD_MATRICULA
WHERE PAUTAS.COD_INSTITUICAO = 3 AND (M.COD_CURSO = 80 OR M.COD_CURSO = 851 OR M.COD_CURSO = 862);

-- Exportação Pessoas
SELECT * FROM PESSOAS INNER JOI
-- Exportação Professores
SELECT * FROM PROFESSORES WHERE COD_INSTITUICAO = 3;


SELECT * FROM TIPOS_CURSOS WHERE COD_TIPO_CURSO = 265;
SELECT * FROM DISCIPLINAS_MATRIZES_CURRICULARES;
SELECT * FROM MATRIZES_CURRICULARES;
-- COD_CURSO
-- 80 (AGRO)
-- 851 (INFO)
-- 862 (MA)
