create table PESSOAS
(
    COD_PESSOA                  int           not null primary key,
    PROFISSAO                   varchar(40),
    COD_GRAU_INSTRUCAO          varchar(5),
    COD_NACIONALIDADE           varchar(5),
    COD_ESTADO_CIVIL            varchar(10),
    COD_CIDADE                  smallint,
    N_FILHOS                    tinyint,
    NOME_PESSOA                 varchar(70)   not null,
    ENDERECO                    varchar(100),
    NUMERO                      varchar(20),
    COMPLEMENTO                 varchar(50),
    CEP                         varchar(10),
    BAIRRO                      varchar(70),
    EMAIL                       varchar(100),
    TEL_RESIDENCIAL             varchar(20),
    TEL_COMERCIAL               varchar(20),
    FAX                         varchar(20),
    URL                         varchar(100),
    CELULAR                     varchar(20),
    CPF                         varchar(20),
    IDENTIDADE_NUMERO           varchar(20),
    SEXO                        char          not null,
    DT_NASCIMENTO               datetime,
    NOME_PAI                    varchar(70),
    NOME_MAE                    varchar(70),
    ESTADO_RESERVISTA           varchar(3),
    TITULO_ELE                  varchar(20),
    ESTADO_IDENTIDADE           varchar(3),
    ZONA_ELE                    varchar(20),
    SECAO_ELE                   varchar(20),
    RESERVISTA                  varchar(30),
    TEXTO_ENCODED               varchar(140),
    COD_NATURALIDADE            smallint,
    ESTADO_TITULO_ELE           varchar(3),
    DATA_TITULO_ELE             smalldatetime,
    TEXTO_SEM_ACENTO            varchar(140),
    COD_ORGAO_EXPEDIDOR         varchar(20),
    DT_CADASTRO                 smalldatetime not null,
    IDENTIDADE_DATA             smalldatetime,
    ANO_RESERVISTA              smallint,
    REGIAO_MILITAR              varchar(10),
    CSM                         varchar(30),
    POSSUI_FOTO                 tinyint       not null,
    TIPO_SANGUINEO              varchar(10),
    COD_CARTORIO                int,
    TIPO_CERTIDAO_CIVIL         tinyint,
    N_TERMO_CERTIDAO_CIVIL      varchar(10),
    FOLHA_CERTIDAO_CIVIL        varchar(10),
    LIVRO_CERTIDAO_CIVIL        varchar(10),
    DT_EMISSAO_CERTIDAO_CIVIL   smalldatetime,
    COD_DISTRITO                int,
    __OBSERVACOES               varchar(255),
    __TRATAMENTO                varchar(4),
    MINICURRICULO               text,
    DT_LIMITE_INTERESSE_EMPREGO smalldatetime,
    PASSAPORTE                  varchar(20),
    ONDE_TRABALHA               varchar(255),
    CARGO                       varchar(255),
    CURSO                       varchar(255),
    ONDE_ESTUDA                 varchar(255),
    MATRICULA_CERTIDAO_CIVIL    varchar(50),
    NOME_SOCIAL                 varchar(70),
    COD_REGISTRO_IMPORTACAO     int,
    DT_ULTIMA_IMPORTACAO        smalldatetime,
    ID_GRUPO_ETNICO             int,
    DOCUMENTO_ESTRANGEIRO       varchar(100),
    NUMERO_CNS                  varchar(50),
    EMANCIPADO                  tinyint       not null
)
go

create table ALUNOS
(
    COD_ALUNO                       int        not null primary key,
    COD_PESSOA                      int        not null,
    COD_ESCOLA_2_GRAU               int,
    COD_ESTADO_CIVIL_PAIS           varchar(10),
    COD_GRAU_INSTRUCAO_PAI          varchar(5),
    COD_GRAU_INSTRUCAO_MAE          varchar(5),
    PAI_FALECIDO                    tinyint,
    MAE_FALECIDA                    tinyint,
    RENDA_FAMILIAR                  smallint,
    TIPO_ESCOLA_ORIGEM              varchar(1),
    RESIDE                          varchar(1),
    ENDERECO_PAIS                   varchar(70),
    NUMERO_PAIS                     varchar(20),
    COMPLEMENTO_PAIS                varchar(50),
    BAIRRO_PAIS                     varchar(70),
    COD_CIDADE_PAIS                 smallint,
    CEP_PAIS                        varchar(10),
    EMAIL_PAIS                      varchar(50),
    TEL_RESIDENCIAL_PAIS            varchar(20),
    TEL_COMERCIAL_PAIS              varchar(20),
    FAX_PAIS                        varchar(20),
    CELULAR_PAIS                    varchar(20),
    ANO_CONCLUSAO_2_GRAU            smallint,
    COR                             varchar(5) not null,
    COD_ESCOLA_1_GRAU               int,
    ANO_CONCLUSAO_1_GRAU            smallint,
    N_PASTA                         varchar(20),
    __N_PROCESSO                    int,
    TIPO_RESPONSAVEL                varchar(1),
    GRAU_PARENTESCO_RESPONSAVEL     varchar(20),
    COD_RESPONSAVEL                 int,
    DESC_CURSO_GRADUACAO            varchar(70),
    COD_DISTRITO_PAIS               int,
    ANO_CONCLUSAO_GRADUACAO         smallint,
    RENDA_PER_CAPITA                tinyint,
    DESC_CURSO_POS_GRADUACAO        varchar(100),
    ANO_CONCLUSAO_POS_GRADUACAO     smallint,
    COD_ESCOLA_GRADUACAO            int,
    NECESSIDADE_FISICA              tinyint,
    COD_ESCOLA_POS_GRADUACAO        int,
    NECESSIDADE_AUDITIVA            tinyint,
    AREA_PROCEDENCIA_ESCOLA_ORIGEM  tinyint,
    NECESSIDADE_VISUAL              tinyint,
    OUTRAS_NECESSIDADES             tinyint,
    DESC_CURSO_2_GRAU               varchar(70),
    RENDA_PER_CAPITA_SIG            tinyint,
    RENDA_PER_CAPITA_INEP           tinyint,
    NECESSIDADE_MENTAL              tinyint,
    NECESSIDADE_MULTIPLA            tinyint,
    CONDUTAS_TIPICAS                tinyint,
    SUPERDOTADO                     tinyint,
    OCUPACAO_RESPONSAVEL            varchar(70),
    SINDROME_DOWN                   tinyint,
    COD_TIPO_TRANSP_ESCOLAR_PUBLICO tinyint,
    RENDA_FAMILIAR_REAIS_SIG        numeric(9, 2),
    N_MEMBROS_FAMILIA               tinyint,
    CONTA_CORRENTE                  varchar(10),
    COD_AGENCIA                     varchar(10),
    COD_BANCO                       varchar(10),
    PIS_PASEP                       varchar(15),
    PODER_PUBLICO_RESP_TRANSPORTE   tinyint    not null,
)
go

create table INSTITUICOES
(
    COD_INSTITUICAO               int          not null primary key,
    DESC_INSTITUICAO              varchar(50)  not null,
    TIPO_INSTITUICAO              tinyint      not null,
    SIGLA_INSTITUICAO             varchar(20),
    ENDERECO                      varchar(100),
    COD_CIDADE                    smallint,
    NUMERO                        varchar(20),
    COMPLEMENTO                   varchar(50),
    CEP                           varchar(10),
    BAIRRO                        varchar(70),
    LATITUDE                      float,
    LONGITUDE                     float,
    COD_DISTRITO                  int,
    COD_PESSOA_DIRETOR            int,
    DESC_CARGO_DIRETOR            varchar(70),
    AUTORIZACAO                   varchar(500),
    CNPJ_INSTITUICAO              varchar(18),
    COD_ESCOLA                    int,
    LEI_ATUAL_CRIACAO_INSTITUICAO varchar(4000),
    FAX                           varchar(100),
    TELEFONE                      varchar(100),
    CERTIFICA_ENEM                tinyint      not null,
    COD_PADRAO_HORARIO_RECURSOS   smallint,
    DESC_INSTITUICAO_DOCUMENTO    varchar(150) not null,
    COD_INSTITUICAO_EMEC          varchar(50)  not null,
    COD_INSTITUICAO_INEP          varchar(50)
)
go

create table CURSOS
(
    COD_CURSO                      int          not null primary key,
    COD_TURNO                      varchar(5)   not null,
    COD_INSTITUICAO                int          not null,
    COD_TIPO_CURSO                 smallint     not null,
    COD_CURSO_HABILITADO           smallint     not null,
    DESC_CURSO                     varchar(255) not null,
    SIGLA_CURSO                    varchar(15)  not null,
    AUTORIZACAO                    varchar(500),
    COD_CURSO_VESTIBULAR           int,
    ATIVO                          tinyint      not null,
    COD_PADRAO_HORARIO             smallint     not null,
    DESC_HISTORICO                 varchar(255) not null,
    CERTIFICADO_CONCLUSAO_CURSO    text,
    TIPO_USUARIO_BIBLIOTECA        tinyint,
    TITULO_CERTIFICADO_CONCLUSAO   varchar(255),
    MODALIDADE_FINANCIAMENTO       tinyint,
    MODALIDADE_CURSO               tinyint,
    RECONHECIMENTO                 varchar(8000),
    PERIODICIDADE_INGRESSANTES     tinyint      not null,
    FINALIDADE_CURSO               text,
    COD_CURSO_MATRICULA            varchar(10)  not null,
    COD_LOCALIZACAO_CURSO          smallint,
    BASE_LEGAL                     varchar(500),
    DT_INICIO                      smalldatetime,
    TIPO_MODALIDADE                tinyint,
    COD_PADRAO_FREQUENCIA          int          not null,
    COD_DEPARTAMENTO               smallint,
    COD_LIVRO_DIPLOMA              int,
    COD_MODELO_FORMULARIO          int,
    COD_CURSO_ESTAGIO              int
        ,
    EXIGE_COLACAO_GRAU             tinyint      not null,
    COD_REGISTRO_ESCOLAR           smallint
        ,
    ATO_CRIACAO                    text,
    EQUIVALENCIA_CARGA_HOR_CREDITO float        not null,
    CONTEUDO_CONTROLADO            tinyint      not null,
    EXIGE_ENADE                    tinyint      not null,
    COD_NORMA_ATIVIDADE            int,
    MODALIDADE_ENSINO              tinyint      not null,
    INTEGRADO_FERRAMENTA_EAD       tinyint      not null,
    COD_PROGRAMA_GOVERNO           int          not null,
    COD_CURSO_APERFEICOAMENTO      int,
    COD_MODELO_FORMULARIO_2VIA     int,
    COD_EAD_INSTANCIA_FERRAMENTA   int,
    COD_EAD_CONFIGURACAO           int,
    POSSUI_CICLO_OFERTA_UNICA      tinyint      not null,
    DESC_CURSO_SIMPLIFICADO        varchar(10)  not null,
    MIN_CREDITOS_PEDIDO_MATRICULA  smallint,
    USAR_DT_COLACAO_NA_CONCLUSAO   tinyint      not null,
    EXIGE_CERTIFICACAO             tinyint      not null,
    COD_CURSO_SISTEC               varchar(50),
    COD_CURSO_EMEC                 varchar(50)
)
go

create table MATRIZES_CURRICULARES
(
	COD_MATRIZ_CURRICULAR int not null primary key,
	N_PERIODOS tinyint not null,
	DT_MATRIZ_CURRICULAR smalldatetime,
	SIT_MATRIZ_CURRICULAR int not null,
	ANO_LET smallint not null,
	PERIODO_LET tinyint not null,
	CARGA_HORARIA_ESTAGIO smallint not null,
	COD_CURSO int not null,
	CARGA_HORARIA_COMPLEMENTAR smallint not null,
	CARGA_HORARIA_OPTATIVA smallint,
	CARGA_HORARIA_MIN_CREDITOS smallint,
	COD_TIPO_CURSO smallint not null,
	N_PERIODOS_JUBILAMENTO tinyint not null,
	N_REPROVACOES_JUBILAMENTO tinyint not null,
	N_PERIODOS_TRANCAMENTO tinyint not null,
	ANO_LET_CONCLUSAO smallint,
	PERIODO_LET_CONCLUSAO tinyint,
	DESC_MATRIZ_CURRICULAR varchar(200),
	CREDITOS_OBRIGATORIOS smallint,
	CARGA_HORARIA_PROJETO_FINAL smallint,
	TIPO_ORIGEM_MATRIZ_CURRICULAR tinyint not null,
	COD_MATRIZ_CURRICULAR_ORIGEM int,
	PERFIL_PROFISSIONAL text,
	BASES_TECNOLOGICAS text,
	TIPO_AVALIACAO_PROJETO_FINAL smallint not null,
	COMPETENCIAS text,
	OBSERVACOES_HISTORICO text,
	EXIGE_SEMINARIO tinyint not null,
	EQUIVALENCIA_CARGA_HOR_CREDITO float not null,
	CONTEUDO_CONTROLADO tinyint not null,
	PERMITE_PRATICA_PROFISSIONAL tinyint not null,
	AUTORIZACAO varchar(500),
	RECONHECIMENTO varchar(500),
	EXIGE_QUALIFICACAO tinyint not null,
	MESES_LIMITE_QUALIFICACAO tinyint,
	COD_MODELO_HISTORICO int,
	COD_MODELO_HISTORICO_PARCIAL int,
	POSSUI_CERTIFICACAO tinyint not null,
	CONTABILIZAR_ESTAGIO_NAO_OBRIG tinyint not null
)
go

create table MATRICULAS
(
    COD_MATRICULA                   int           not null primary key,
    COD_CURSO                       int           not null,
    COD_CLASSIFICADO                int,
    COD_ALUNO                       int           not null,
    COD_HABILITACAO                 int           not null,
    COD_MATRIZ_CURRICULAR           int           not null,
    COD_FORMA_INGRESSO              varchar(10)   not null,
    COD_INSTITUICAO                 int           not null,
    MATRICULA                       varchar(20)   not null,
    ANO_LETIVO_INI                  smallint      not null,
    PERIODO_LETIVO_INI              tinyint       not null,
    SIT_MATRICULA                   tinyint       not null,
    DT_MATRICULA                    smalldatetime not null,
    PERIODO_ATUAL                   int           not null,
    __DIPLOMA_N_REGISTRO            int,
    COEFICIENTE_RENDIMENTO          numeric(5, 2) not null,
    __DIPLOMA_N_LIVRO               smallint,
    __DIPLOMA_N_FOLHA               smallint,
    __DIPLOMA_DATA                  smalldatetime,
    __DIPLOMA_PROCESSO              varchar(50),
    __DT_CONCLUSAO_ENSINO_MEDIO     smalldatetime,
    __DT_CONCLUSAO_CURSO            smalldatetime,
    __RESULTADO_VESTIBULAR          text,
    SENHA                           varchar(100),
    __DIPLOMA_VIA                   tinyint,
    COD_TURNO                       varchar(5),
    __DIPLOMA_SERIE                 varchar(20),
    __DIPLOMA_PASTA                 varchar(20),
    COD_TURMA_ATUAL                 varchar(50),
    ANO_LET_ATUAL                   smallint,
    PERIODO_LET_ATUAL               tinyint,
    DT_INICIO_INSCRICAO_ESTAGIO     smalldatetime,
    CLASSIFICACAO_SELECAO           int,
    DT_FINAL_INSCRICAO_ESTAGIO      smalldatetime,
    SENHA_PAIS                      varchar(50),
    TIPO_CONCOMITANCIA              tinyint       not null,
    __N_PROCESSO                    int,
    DT_LIMITE_QUALIFICACAO          smalldatetime,
    NOTAS_SELECAO                   varchar(2000),
    DT_EXAME_QUALIFICACAO           smalldatetime,
    SIT_QUALIFICACAO                tinyint       not null,
    DT_INTEGRALIZACAO_CARGA_HORARIA smalldatetime,
    DT_LIMITE_DEFESA                smalldatetime,
    DT_COLACAO_GRAU                 smalldatetime,
    VIA                             tinyint,
    TIPO_USUARIO_BIBLIOTECA         smallint,
    CIA                             varchar(20),
    DT_EXAME_NACIONAL_CURSOS        smalldatetime,
    REGIME_INTERNATO                tinyint       not null,
    OBSERVACOES_GERAIS              varchar(1000),
    ANO_LET_CONCLUSAO               smallint,
    PERIODO_LET_CONCLUSAO           tinyint,
    DT_INSERCAO                     smalldatetime not null,
    COD_CRACHA                      varchar(20),
    COD_EAD_POLO                    int,
    OBSERVACOES_DESTAQUE            varchar(1000),
    BOLSA_FAMILIA                   tinyint,
    BOLSA_ESCOLA                    tinyint,
    uidNumber                       int identity (48001, 1),
    ANO_LET_PREV_CONCLUSAO          int,
    PERIODO_LET_PREV_CONCLUSAO      int,
    COEFICIENTE_PROGRESSAO          numeric(5, 2) not null,
    __INSTITUICAO_DIPLOMA           varchar(255),
    INSCRICAO_SEMINARIO_LIBERADA    tinyint       not null,
    SIT_MATRICULA_OLD               tinyint,
    COD_LIVRO_DIPLOMA               int,
    N_INSCRICAO_ENEM                varchar(20),
    SIT_ENADE                       tinyint       not null,
    DT_ULTIMO_ENADE                 smalldatetime,
    ANO_LET_INTEGRALIZACAO_CH       smallint,
    PERIODO_LET_INTEGRALIZACAO_CH   tinyint,
    __DIPLOMA_L_LIVRO               varchar(10),
    Sit_Validacao_Migracao          tinyint       not null,
    __DIPLOMA_SISTEC                varchar(30),
    __DIPLOMA_DATA_EMISSAO          smalldatetime,
    __DIPLOMA_N_REGISTRO_ANT        int,
    __DIPLOMA_N_LIVRO_ANT           smallint,
    __DIPLOMA_N_FOLHA_ANT           smallint,
    __DIPLOMA_DATA_ANT              smalldatetime,
    __DIPLOMA_PROCESSO_ANT          varchar(50),
    __DIPLOMA_VIA_ANT               tinyint,
    __DIPLOMA_SERIE_ANT             varchar(20),
    __DIPLOMA_PASTA_ANT             varchar(20),
    __DIPLOMA_L_LIVRO_ANT           varchar(10),
    __DIPLOMA_SISTEC_ANT            varchar(30),
    __DIPLOMA_DATA_EMISSAO_ANT      smalldatetime,
    LDAP_DN                         varchar(1000),
    COTA                            tinyint,
    COD_MATRIZ_INI                  int,
    EXIBIR_OBSERVACOES_HISTORICO    tinyint       not null,
    ALTEROU_CONCLUSAO_MANUALMENTE   tinyint       not null,
    OBSERVACOES_HISTORICO           varchar(8000),
    COD_TURNO_INI                   varchar(5),
    DT_CONCURSO                     smalldatetime,
    COD_PUBLICACAO_DIARIO_OFICIAL   int
)
go

create table PROFESSORES
(
    COD_PROFESSOR                   int         not null primary key,
    COD_PESSOA                      int         not null,
    COD_INSTITUICAO                 int         not null,
    TITULARIDADE                    tinyint,
    DT_ADMISSAO                     smalldatetime,
    CTPS                            varchar(20),
    SERIE_CTPS                      varchar(20),
    ID_FUNCIONARIO                  varchar(20) not null,
    OBSERVACOES                     text,
    NOME_USUAL                      varchar(30) not null,
    TIPO_REGIME_TRABALHO            tinyint     not null,
    SIT_PROFESSOR                   tinyint     not null,
    RAMAL                           varchar(5),
    DT_INICIO_CONTRATO              smalldatetime,
    TIPO_MODALIDADE_CONTRATACAO     tinyint     not null,
    DT_TERMINO_CONTRATO             smalldatetime,
    NOME_INSTITUICAO_PROF_CONVIDADO varchar(30),
    TIPO_USUARIO_BIBLIOTECA         smallint,
    OBSERVACOES_SITUACAO            text,
    ESPACO_MATERIAL_AULA            int,
    PIS_PASEP                       varchar(20),
    CONTA_CORRENTE                  varchar(10),
    COD_AGENCIA                     varchar(10),
    COD_BANCO                       varchar(10),
    TIPO_VINCULO                    tinyint,
    COD_CRACHA                      varchar(20),
    EAD                             tinyint     not null,
    COD_EAD_POLO                    int,
    COR                             varchar(5)  not null,
    COD_DEPARTAMENTO                smallint,
    CONDUTAS_TIPICAS                tinyint,
    NECESSIDADE_AUDITIVA            tinyint,
    NECESSIDADE_MULTIPLA            tinyint,
    OUTRAS_NECESSIDADES             tinyint,
    SUPERDOTADO                     tinyint,
    NECESSIDADE_FISICA              tinyint,
    NECESSIDADE_MENTAL              tinyint,
    NECESSIDADE_VISUAL              tinyint,
    TIPO_CADASTRO                   tinyint     not null,

)
go

create table TURMAS
(
    COD_TURMA                    varchar(50)  not null primary key,
    COD_HABILITACAO              int          not null,
    COD_MODULO                   int,
    COD_INSTITUICAO              int          not null,
    COD_MATRIZ_CURRICULAR        int          not null,
    COD_CURSO                    int          not null,
    DESC_TURMA                   varchar(255) not null,
    ANO_LET                      smallint     not null,
    PERIODO_LET                  tinyint      not null,
    PERIODO                      tinyint      not null,
    N_VAGAS                      smallint     not null,
    SIT_TURMA                    int,
    COD_TURNO                    varchar(5)   not null,
    COD_PADRAO_HORARIO           smallint     not null,
    SIGLA_TURMA                  varchar(20)  not null,
    POSSUI_DADOS_EXPORTADOS_EAD  tinyint,
    COD_EAD_POLO                 int,
    COD_EAD_INSTANCIA_FERRAMENTA int,
    TIPO_TURMA                   tinyint      not null,
    INDICE_TURMAS                int identity,

)
go

create table DISCIPLINAS
(
	COD_DISCIPLINA int not null primary key,
	DESC_DISCIPLINA varchar(255) not null,
	CARGA_HOR float not null,
	DESC_HISTORICO varchar(255) not null,
	TEXTO_SEM_ACENTO varchar(255),
	TEXTO_ENCODED varchar(255),
	SIGLA_DISCIPLINA varchar(20) not null,
	ATIVA smallint not null,
	N_RECOMENDADO_ALUNOS int,
	NIVEL_ENSINO varchar(3) not null,
	REGIME_COMPETENCIA tinyint,
	COD_TIPO_DISCIPLINA_ESPECIAL smallint,
	TIPO_DISCIPLINA tinyint not null,
	DESC_DISCIPLINA_SIMPLIFICADO varchar(10) not null,
	CARGA_HOR_TEORICA smallint,
	CARGA_HOR_PRATICA smallint,
	CARGA_HOR_SEMANAL float,
	COD_DEPARTAMENTO smallint,
	CONTEUDO_CONTROLADO tinyint not null,
	CONFIG_SIGLA_MANUALMENTE tinyint
)
go

create table PAUTAS
(
    COD_PAUTA                     int           not null primary key,
    COD_TIPO_CURSO                smallint      not null,
    COD_CALENDARIO                smallint,
    COD_INSTITUICAO               int           not null,
    COD_PROFESSOR                 int,
    COD_DISCIPLINA                int           not null,
    COD_TURMA                     varchar(50),
    DESC_PAUTA                    varchar(255),
    N_TURMA                       tinyint,
    FORMA_CALCULO_MEDIA           tinyint,
    N_VAGAS                       smallint      not null,
    ANO_LET                       smallint      not null,
    PERIODO_LET                   tinyint       not null,
    SIT_PAUTA                     tinyint       not null,
    DT_INICIO                     smalldatetime not null,
    DT_FINAL                      smalldatetime not null,
    BLOCO                         varchar(10),
    TEXTO_ENCODED                 varchar(255),
    TEXTO_SEM_ACENTO              varchar(255),
    SIT_ENTREGA_COMPETENCIAS      tinyint,
    TIPO_PAUTA                    tinyint,
    PESO_TEORICA                  numeric(5, 2),
    PESO_PRATICA                  numeric(5, 2),
    COD_PAUTA_RELACIONADA         int,
    COD_PADRAO_HORARIO            smallint      not null,
    COD_TURNO                     varchar(5)    not null,
    DESC_HORARIO                  varchar(255),
    DESABILITAR_FAQS              tinyint,
    COD_EAD_INSTANCIA_FERRAMENTA  int,
    COD_EAD_POLO                  int,
    POSSUI_DADOS_EXPORTADOS_EAD   tinyint,
    COD_PADRAO_FREQUENCIA         int           not null,
    PROFESSORES                   varchar(800),
    EXIBIR_DESC_PAUTA             tinyint       not null,
    CARGA_HOR_PRESENCIAL          float         not null,
    PER_MIN_CH_CUMPRIDA           numeric(5, 2) not null,
    CAMPO_ORDENACAO_1             varchar(50),
    CAMPO_ORDENACAO_2             varchar(50),
    CAMPO_ORDENACAO_3             varchar(50),
    COD_OFERTA_ESTAGIO_CURRICULAR int,
    SIT_HORARIO_PAUTA             tinyint       not null,
    DT_LIMITE_POSSE_REGISTRO      smalldatetime,
    SIT_FERIAS                    tinyint       not null,
    CONTEUDO_CONTROLADO           tinyint,
)
go

create table DISCIPLINAS_MATRIZES_CURRICULARES
(
	COD_MATRIZ_CURRICULAR int not null,
	COD_DISCIPLINA int not null,
	COD_HABILITACAO int not null,
	N_PERIODO tinyint not null,
	OPTATIVA tinyint not null,
	CREDITOS decimal(15,2),
	NUCLEO_DISCIPLINA tinyint not null,
	CREDITOS_NECESSARIOS smallint not null,
	COD_MODULO int,
	ORDEM tinyint,
	COD_TIPO_CURSO smallint not null,
	NAO_PERMITE_DEPENDENCIA tinyint not null,
	CARGA_HOR_PRESENCIAL float not null,
	COD_MATERIA int,
	TIPO_DISCIPLINA tinyint not null,
	POSSUI_PRATICA_PROFISSIONAL tinyint not null,
	CARGA_HOR_PRATICA_PROFISSIONAL float,
	OPTATIVA_EXCLUSIVA tinyint not null,
	GRUPO_OPTATIVA_EXCLUSIVA int,
	EXIBICAO_HISTORICO tinyint not null,
	COD_EAD_CURSO_MODELO int,
    primary key (COD_MATRIZ_CURRICULAR, COD_DISCIPLINA, COD_HABILITACAO)
)
go

create table ETAPAS
(
	N_ETAPA varchar(10) not null,
	COD_TIPO_CURSO smallint not null,
	COD_TIPO_NOTA varchar(5) not null,
	DESC_ETAPA varchar(50) not null,
	PRECISA_SER_ENTREGUE tinyint not null,
	ABREVIACAO varchar(10) not null,
	NOTA_MAX numeric(5,2) not null,
	MENOR_UNI numeric(5,2) not null,
	ORDEM_ETAPA smallint not null,
	PESO_NOTA tinyint not null,
	EXIBIR_ETAPA tinyint,
	FORMA_CALCULO tinyint,
	EXIGE_FALTAS tinyint not null,
	NOTA_MIN float not null,
	EXIBIR_NO_HISTORICO tinyint not null,
	MEDIA_MAX float not null,
	OPCIONAL tinyint not null,
	EXIBIR_DIARIO tinyint not null,
	EXIGIR_INSCRICAO tinyint not null,
	N_MAX_INSCRICOES smallint,
	DESC_ETAPA_MOODLE varchar(255),
	TIPO_IMPORTACAO_NOTA tinyint not null,
	TIPO_IMPORTACAO_FREQUENCIA tinyint not null,
	EXIBIR_ETAPA_SIMPLIFICADO tinyint,
)
go

create table TIPOS_NOTAS
(
	COD_TIPO_NOTA varchar(5) not null primary key,
	DESC_TIPO_NOTA varchar(50) not null,
	CONTEUDO_CONTROLADO tinyint
)
go

create table TIPOS_CURSOS
(
	COD_TIPO_CURSO smallint not null primary key,
	DESC_TIPO_CURSO varchar(50) not null,
	ATIVO tinyint not null,
	TIPO_AVALIACAO tinyint not null,
	MEDIA_PROVA_FIN numeric(5,2) not null,
	MODULAR tinyint not null,
	PERIODIZADO tinyint not null,
	MEDIA_FIN numeric(5,2) not null,
	MATRICULA_MODULO tinyint not null,
	NOTA_MAX numeric(7,2),
	REGIME_COMPETENCIA tinyint not null,
	N_PERIODOS_ANO tinyint not null,
	DESC_PERIODO varchar(20) not null,
	CRITERIO_ARREDONDAMENTO tinyint not null,
	PERCENTUAL_PRESENCA_REPROVACAO numeric(5,2) not null,
	MENOR_UNI numeric(5,2) not null,
	MEDIA_REPROVACAO numeric(5,2) not null,
	CRITERIO_MEDIA_PERIODO tinyint,
	CRITERIO_MEDIA_PROVA_FINAL tinyint,
	MAXIMO_REPROVACOES tinyint,
	MAXIMO_REPROVACOES_AREA tinyint,
	MAPEAR_NOTA_EM_CONCEITO tinyint not null,
	MODULAR_RN tinyint,
	MAXIMO_REPROVACOES_CONSELHO tinyint,
	PERMITE_DISPENSA tinyint not null,
	PERCENTUAL_MINIMO_COMPETENCIA tinyint not null,
	PERCENTUAL_PRESENCA_DISCIPLINA tinyint not null,
	MULTIPLOS_MODULOS tinyint,
	FREQUENCIA_ALTERNATIVA float not null,
	MEDIA_FREQUENCIA_ALTERNATIVA float not null,
	RENDIMENTO_GLOBAL tinyint not null,
	PERMITE_SOMENTE_DEPENDENCIAS tinyint not null,
	FORMA_CONTROLE_DEPENDENCIAS tinyint not null,
	GERAR_DEPENDENCIAS_NAO_CURSADAS tinyint not null,
	LIMITE_PROVAS_FINAIS tinyint not null,
	FREQUENCIA_PROVA_FINAL tinyint not null,
	MEDIA_FREQUENCIA_PROVA_FINAL tinyint not null,
	MEDIA_PERMITE_DEPENDENCIA tinyint not null,
	CONSIDERAR_ELETIVAS tinyint not null,
	CONSIDERAR_OPTATIVAS tinyint not null,
	PERCENTUAL_PRESENCA_DEPENDENCIA numeric(5,2),
	CONTEUDO_CONTROLADO tinyint not null,
	CONSIDERAR_DEP_FREQ_GLOBAL int not null,
	CONSIDERAR_DEP_APROVEITAMENTO int not null,
	CONSIDERAR_DEPENDENCIAS tinyint not null,
	CONSIDERAR_EXTRAS tinyint not null,
	LIMITE_DISCIPLINAS_NOTA_MINIMA tinyint,
	NOTA_MINIMA_EXIGIDA numeric(5,2),
	MEDIA_ACELERACAO numeric(5,2) not null,
	CRITERIO_ARREDONDAMENTO_FREQ_AP tinyint,
	CRITERIO_ARREDONDAMENTO_FREQ_EX tinyint,
	MENOR_UNI_FREQ_AP numeric(5,2),
	MENOR_UNI_FREQ_EX numeric(5,2),
	CONSIDERAR_NAO_CURSADAS tinyint not null,
	LIMITE_RECORRENCIA_REPROVACAO tinyint not null
)
go

create table AVALIACOES
(
	COD_AVALIACAO int not null primary key,
	DESC_AVALIACAO varchar(150) not null,
	PESO numeric(5,2),
	TIPO_AVALIACAO tinyint not null,
	COD_PAUTA int not null,
	N_ETAPA varchar(10) not null,
	DT_AVALIACAO smalldatetime,
	ORDEM tinyint not null,
	INDICE tinyint,
	NOTA_MAX float,
	FORMA_CALCULO_MEDIA tinyint,
	DESCARTAR_MAIOR_NOTA tinyint,
	DESCARTAR_MENOR_NOTA tinyint,
	GRADE_ITEM_ID int,
	SIGLA varchar(5) not null,
	FORMULA varchar(255),
	MEDIA_VALIDA tinyint,
)
go

create table MATRICULAS_AVALIACOES
(
	COD_AVALIACAO int not null,
	OBSERVACOES varchar(255),
	NOTA numeric(5,2),
	COD_MATRICULA int not null,
	primary key (COD_AVALIACAO, COD_MATRICULA)
)
go

create table NOTAS
(
	COD_MATRICULA int not null,
	COD_PAUTA int not null,
	N1 float,
	N2 float,
	N3 float,
	N4 float,
	N5 float,
	N6 float,
	N7 float,
	N8 float,
	N9 float,
	N10 float,
	F1 smallint,
	F2 smallint,
	F3 smallint,
	F4 smallint,
	F5 smallint,
	F6 smallint,
	F7 smallint,
	F8 smallint,
	F9 smallint,
	F10 smallint,
	AD1 varchar(50),
	AD2 varchar(50),
	AD3 varchar(50),
	AD4 varchar(50),
	AD5 varchar(50),
	AD6 varchar(50),
	AD7 varchar(50),
	AD8 varchar(50),
	AD9 varchar(50),
	AD10 varchar(50),
	R1 tinyint,
	R2 tinyint,
	R3 tinyint,
	R4 tinyint,
	R5 tinyint,
	R6 tinyint,
	R7 tinyint,
	R8 tinyint,
	R9 tinyint,
	R10 tinyint,
	O1 smallint,
	O2 smallint,
	O3 smallint,
	O4 smallint,
	O5 smallint,
	O6 smallint,
	O7 smallint,
	O8 smallint,
	O9 smallint,
	O10 smallint,
	N11 float,
	N12 float,
	N13 float,
	N14 float,
	N15 float,
	N16 float,
	F11 smallint,
	F12 smallint,
	F13 smallint,
	F14 smallint,
	F15 smallint,
	F16 smallint,
	AD11 varchar(50),
	AD12 varchar(50),
	AD13 varchar(50),
	AD14 varchar(50),
	AD15 varchar(50),
	AD16 varchar(50),
	R11 tinyint,
	R12 tinyint,
	R13 tinyint,
	R14 tinyint,
	R15 tinyint,
	R16 tinyint,
	O11 smallint,
	O12 smallint,
	O13 smallint,
	O14 smallint,
	O15 smallint,
	O16 smallint,
	N17 float,
	N18 float,
	N19 float,
	N20 float,
	N21 float,
	N22 float,
	N23 float,
	N24 float,
	N25 float,
	F17 smallint,
	F18 smallint,
	F19 smallint,
	F20 smallint,
	F21 smallint,
	F22 smallint,
	F23 smallint,
	F24 smallint,
	F25 smallint,
	AD17 varchar(50),
	AD18 varchar(50),
	AD19 varchar(50),
	AD20 varchar(50),
	AD21 varchar(50),
	AD22 varchar(50),
	AD23 varchar(50),
	AD24 varchar(50),
	AD25 varchar(50),
	R17 tinyint,
	R18 tinyint,
	R19 tinyint,
	R20 tinyint,
	R21 tinyint,
	R22 tinyint,
	R23 tinyint,
	R25 tinyint,
	R24 tinyint,
	O17 smallint,
	O18 smallint,
	O19 smallint,
	O20 smallint,
	O21 smallint,
	O22 smallint,
	O23 smallint,
	O24 smallint,
	O25 smallint,
	N26 float,
	N27 float,
	N28 float,
	N29 float,
	N30 float,
	N31 float,
	N32 float,
	N33 float,
	N34 float,
	N35 float,
	N36 float,
	N37 float,
	N38 float,
	N39 float,
	N40 float,
	F26 smallint,
	F27 smallint,
	F28 smallint,
	F29 smallint,
	F30 smallint,
	F31 smallint,
	F32 smallint,
	F33 smallint,
	F34 smallint,
	F35 smallint,
	F36 smallint,
	F37 smallint,
	F38 smallint,
	F39 smallint,
	F40 smallint,
	AD26 varchar(50),
	AD27 varchar(50),
	AD28 varchar(50),
	AD29 varchar(50),
	AD30 varchar(50),
	AD31 varchar(50),
	AD32 varchar(50),
	AD33 varchar(50),
	AD34 varchar(50),
	AD35 varchar(50),
	AD36 varchar(50),
	AD37 varchar(50),
	AD38 varchar(50),
	AD39 varchar(50),
	AD40 varchar(50),
	R26 tinyint,
	R27 tinyint,
	R28 tinyint,
	R29 tinyint,
	R30 tinyint,
	R31 tinyint,
	R32 tinyint,
	R33 tinyint,
	R34 tinyint,
	R35 tinyint,
	R36 tinyint,
	R37 tinyint,
	R38 tinyint,
	R39 tinyint,
	R40 tinyint,
	O26 smallint,
	O27 smallint,
	O28 smallint,
	O29 smallint,
	O30 smallint,
	O31 smallint,
	O32 smallint,
	O33 smallint,
	O34 smallint,
	O35 smallint,
	O36 smallint,
	O37 smallint,
	O38 smallint,
	O39 smallint,
	O40 smallint,
	q_cod_matriz_curricular int,
	q_cod_disciplina int,
	q_cod_pauta int,
	q_sit_matricula_Pauta int,
	migrar int
    )
go

create table VW_PROFESSORES_FUNCIONARIOS
(
	COD_PESSOA int,
	COD_PROFESSOR int,
	NOME varchar,
	NOME_PESSOA varchar,
	NOME_USUAL varchar,
	TEXTO_SEM_ACENTO varchar,
	TEXTO_ENCODED varchar,
	CODIGO int,
	ID_FUNCIONARIO varchar,
	COD_DEPARTAMENTO smallint,
	TITULARIDADE tinyint,
	SIT_FUNCIONARIO varchar,
	SIT_PROFESSOR tinyint,
	COD_INSTITUICAO int,
	TIPO varchar,
	ATIVO int
)
go


create table MEDIDAS_DISCIPLINARES
(
	COD_MEDIDA_DISCIPLINAR int not null
			primary key,
	COD_MATRICULA int,
	COD_TIPO_MEDIDA_DISCIPLINAR int not null,
	DT_MEDIDA_DISCIPLINAR smalldatetime not null,
	OBSERVACOES varchar(4000),
	TIPO_USUARIO tinyint not null,
	COD_PROFESSOR int,
	COD_FUNCIONARIO int

)
go

create table TIPOS_MEDIDAS_DISCIPLINARES
(
	COD_TIPO_MEDIDA_DISCIPLINAR int not null
			primary key,
	DESC_TIPO_MEDIDA_DISCIPLINAR varchar(70) not null,
	CONTEUDO_CONTROLADO tinyint not null,
	TIPO_USUARIO tinyint not null
)
go










